export enum EditProfileStates {
  COMMENT = 'EDIT_COMMENT',
  PAYMENT = 'EDIT_PAYMENT',
  PHOTO_UPLOAD = 'EDIT_PHOTO_UPLOAD',
  COUNTRY = 'EDIT_COUNTRY',
  COUNTRY_INPUT = 'EDIT_COUNTRY_INPUT',
  CITY = 'EDIT_CITY',
  CITY_INPUT = 'EDIT_CITY_INPUT',
  SPORT = 'EDIT_SPORT',
  ROLE = 'EDIT_ROLE',
  PRICE = 'EDIT_PRICE',
  LEVEL = 'EDIT_LEVEL',
  DATING_GOAL = 'EDIT_DATING_GOAL',
  DATING_INTERESTS = 'EDIT_DATING_INTERESTS',
  DATING_ADDITIONAL = 'EDIT_DATING_ADDITIONAL',
  MEETING_TIME = 'EDIT_MEETING_TIME',
}

export enum RegistrationStates {
  REGISTRATION_START = 'REGISTRATION_START',
  PHONE = 'PHONE',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  BIRTH_DATE = 'BIRTH_DATE',
  COUNTRY = 'COUNTRY',
  CITY = 'CITY',
  ROLE = 'ROLE',
  TRAINER_PRICE = 'TRAINER_PRICE',
  SPORT = 'SPORT',
  GENDER = 'GENDER',
  PLAYER_LEVEL = 'PLAYER_LEVEL',
  PHOTO = 'PHOTO',
  SHOW_IN_SEARCH = 'SHOW_IN_SEARCH',
  VACATION_TENNIS = 'VACATION_TENNIS',
  VACATION_START = 'VACATION_START',
  VACATION_END = 'VACATION_END',
  VACATION_COMMENT = 'VACATION_COMMENT',
  COUNTRY_INPUT = 'COUNTRY_INPUT',
  CITY_INPUT = 'CITY_INPUT',
  PROFILE_COMMENT = 'PROFILE_COMMENT',
  DEFAULT_PAYMENT = 'DEFAULT_PAYMENT',
  VACATION_COUNTRY = 'VACATION_COUNTRY',
  VACATION_COUNTRY_INPUT = 'VACATION_COUNTRY_INPUT',
  VACATION_CITY = 'VACATION_CITY',
  VACATION_CITY_INPUT = 'VACATION_CITY_INPUT',
  DATING_GOAL = 'DATING_GOAL',
  DATING_INTERESTS = 'DATING_INTERESTS',
  DATING_ADDITIONAL = 'DATING_ADDITIONAL',
  MEETING_TIME = 'MEETING_TIME',
  TABLE_TENNIS_RATING = 'TABLE_TENNIS_RATING',
}

export enum GameOfferStates {
  GAME_SPORT = 'GAME_SPORT',
  GAME_COUNTRY = 'GAME_COUNTRY',
  GAME_COUNTRY_INPUT = 'GAME_COUNTRY_INPUT',
  GAME_CITY = 'GAME_CITY',
  GAME_CITY_INPUT = 'GAME_CITY_INPUT',
  GAME_DISTRICT = 'GAME_DISTRICT',
  GAME_DATE = 'GAME_DATE',
  GAME_DATE_MANUAL = 'GAME_DATE_MANUAL',
  GAME_TIME = 'GAME_TIME',
  GAME_TYPE = 'GAME_TYPE',
  PAYMENT_TYPE = 'PAYMENT_TYPE',
  GAME_COMPETITIVE = 'GAME_COMPETITIVE',
  GAME_REPEAT = 'GAME_REPEAT',
  GAME_COMMENT = 'GAME_COMMENT',
  DATING_GOAL = 'DATING_GOAL',
  DATING_INTERESTS = 'DATING_INTERESTS',
  DATING_ADDITIONAL = 'DATING_ADDITIONAL',
}

export enum SearchPartnerStates {
  SEARCH_TYPE = 'SEARCH_TYPE',
  SEARCH_COUNTRY = 'SEARCH_COUNTRY',
  SEARCH_COUNTRY_INPUT = 'SEARCH_COUNTRY_INPUT',
  SEARCH_CITY = 'SEARCH_CITY',
  SEARCH_CITY_INPUT = 'SEARCH_CITY_INPUT',
  SEARCH_SPORT = 'SEARCH_SPORT',
  SEARCH_GENDER = 'SEARCH_GENDER',
  SEARCH_LEVEL = 'SEARCH_LEVEL',
  SEARCH_PRICE_RANGE = 'SEARCH_PRICE_RANGE',
  SEARCH_RESULTS = 'SEARCH_RESULTS',
  SEARCH_NO_RESULTS = 'SEARCH_NO_RESULTS',
  SEARCH_ERROR = 'SEARCH_ERROR',
  SEARCH_OTHER_COUNTRIES = 'SEARCH_OTHER_COUNTRIES',
  SEARCH_OTHER_CITIES = 'SEARCH_OTHER_CITIES',
  SEARCH_DISTRICT = 'SEARCH_DISTRICT',
  SEARCH_AGE_RANGE = 'SEARCH_AGE_RANGE',
  SEARCH_DATING_GOAL = 'SEARCH_DATING_GOAL',
  SEARCH_DISTANCE = 'SEARCH_DISTANCE',
}

export enum AddScoreState {
  SELECTING_GAME_TYPE = 'selecting_game_type',
  SELECTING_PARTNER = 'selecting_partner',
  SEARCHING_PARTNER = 'searching_partner',
  SELECTING_OPPONENT = 'selecting_opponent',
  SEARCHING_OPPONENT = 'searching_opponent',
  SELECTING_SET_SCORE = 'selecting_set_score',
  ADDING_ANOTHER_SET = 'adding_another_set',
  ADDING_MEDIA = 'adding_media',
  CONFIRMING_SCORE = 'confirming_score',
  SEARCHING_OPPONENT1 = 'searching_opponent1',
  SEARCHING_OPPONENT2 = 'searching_opponent2',
  SELECTING_OPPONENT1 = 'selecting_opponent1',
  SELECTING_OPPONENT2 = 'selecting_opponent2',
  SELECTING_TOURNAMENT = 'selecting_tournament',
  SELECTING_TOURNAMENT_OPPONENT = 'selecting_tournament_opponent',
}

export enum PaymentStates {
  WAITING_EMAIL = 'WAITING_EMAIL',
  CONFIRM_PAYMENT = 'CONFIRM_PAYMENT',
}

export enum TournamentPaymentStates {
  WAITING_EMAIL = 'TOURNAMENT_WAITING_EMAIL',
  CONFIRM_PAYMENT = 'TOURNAMENT_CONFIRM_PAYMENT',
}

export enum AdminBroadcastStates {
  WAIT_FORWARD = 'WAIT_FORWARD',
  MANUAL_MEDIA = 'MANUAL_MEDIA',
  MANUAL_TEXT = 'MANUAL_TEXT',
  CONFIRM = 'CONFIRM',
}

export enum AdminSubscriptionStates {
  SEARCH_USER = 'ADMIN_SUB_SEARCH_USER',
  EDIT_UNTIL = 'ADMIN_SUB_EDIT_UNTIL',
  EDIT_ACTIVATED = 'ADMIN_SUB_EDIT_ACTIVATED',
  EDIT_EMAIL = 'ADMIN_SUB_EDIT_EMAIL',
}

export enum BrowseOffersStates {
  SELECT_SPORT = 'SELECT_SPORT',
  SELECT_COUNTRY = 'SELECT_COUNTRY',
  SELECT_CITY = 'SELECT_CITY',
  LIST = 'LIST',
  VIEW = 'VIEW',
  RESPOND = 'RESPOND',
}

export enum BrowseToursStates {
  SELECT_SPORT = 'SELECT_SPORT',
  SELECT_COUNTRY = 'SELECT_COUNTRY',
  SELECT_CITY = 'SELECT_CITY',
  LIST = 'LIST',
}

export enum FindCoachStates {
  SEARCH_SPORT = 'FIND_COACH_SPORT',
  SEARCH_PRICE_RANGE = 'FIND_COACH_PRICE_RANGE',
  SEARCH_COUNTRY = 'FIND_COACH_COUNTRY',
  SEARCH_OTHER_COUNTRIES = 'FIND_COACH_OTHER_COUNTRIES',
  SEARCH_CITY = 'FIND_COACH_CITY',
  SEARCH_OTHER_CITIES = 'FIND_COACH_OTHER_CITIES',
  SEARCH_RESULTS = 'FIND_COACH_RESULTS',
  SEARCH_NO_RESULTS = 'FIND_COACH_NO_RESULTS',
}

export enum AllPlayersStates {
  SEARCH_SPORT = 'ALL_PLAYERS_SPORT',
  SEARCH_COUNTRY = 'ALL_PLAYERS_COUNTRY',
  SEARCH_OTHER_COUNTRIES = 'ALL_PLAYERS_OTHER_COUNTRIES',
  SEARCH_CITY = 'ALL_PLAYERS_CITY',
  SEARCH_OTHER_CITIES = 'ALL_PLAYERS_OTHER_CITIES',
  SEARCH_RESULTS = 'ALL_PLAYERS_RESULTS',
  SEARCH_NO_RESULTS = 'ALL_PLAYERS_NO_RESULTS',
}

export enum CreateTourStates {
  COUNTRY = 'COUNTRY',
  CITY = 'CITY',
  START_DATE = 'START_DATE',
  END_DATE = 'END_DATE',
  COMMENT = 'COMMENT',
}

export enum CreateTournamentStates {
  SPORT = 'SPORT',
  COUNTRY = 'COUNTRY',
  CITY = 'CITY',
  DISTRICT = 'DISTRICT',
  TYPE = 'TYPE',
  GENDER = 'GENDER',
  CATEGORY = 'CATEGORY',
  AGE_GROUP = 'AGE_GROUP',
  DURATION = 'DURATION',
  PARTICIPANTS_COUNT = 'PARTICIPANTS_COUNT',
  SHOW_IN_LIST = 'SHOW_IN_LIST',
  HIDE_BRACKET = 'HIDE_BRACKET',
  COMMENT = 'COMMENT',
  CONFIRM = 'CONFIRM',
}

export enum ViewTournamentsStates {
  SPORT = 'SPORT',
  COUNTRY = 'COUNTRY',
  COUNTRY_INPUT = 'TOURNAMENT_COUNTRY_INPUT',
  CITY = 'CITY',
  CITY_INPUT = 'TOURNAMENT_CITY_INPUT',
  DISTRICT = 'DISTRICT',
  GENDER = 'GENDER',
  TYPE = 'TYPE',
  LIST = 'LIST',
  PROPOSED = 'PROPOSED',
}
