export function fmt(template: string, params: Record<string, string | number>): string {
  return Object.entries(params).reduce(
    (text, [k, v]) => text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v)),
    template,
  );
}

export const TXT = {
  common: {
    back: '◀️ Назад',
    cancel: '❌ Отмена',
    skip: '⏭ Пропустить',
    yes: '✅ Да',
    no: '❌ Нет',
    main_menu: '🏠 Главное меню',
    next: '▶️ Далее',
    prev: '◀️ Назад',
    confirm: '✅ Подтвердить',
    banned: '⛔ Вы заблокированы и не можете пользоваться ботом.',
    private_only: '💬 Бот работает только в личных сообщениях. Напишите ему в личку.',
    error: '⚠️ Произошла ошибка. Попробуйте ещё раз чуть позже.',
    not_registered: '👋 Сначала пройдите регистрацию — нажмите /start',
  },
  menu: {
    search_partner: '🎾 Поиск партнера',
    game_offers: '⏱ Предложение игр',
    tournaments: '🏆 Турниры',
    enter_score: '📝 Внести счет',
    invite: '🔗 Пригласить друга',
    payments: '💳 Платежи',
    more: '🔍 Еще',
  },
  registration: {
    welcome:
      '👋 Добро пожаловать в Tennis-Play!\n\nДавайте быстро создадим ваш профиль — это займёт пару минут.\n\nНачиная регистрацию, вы соглашаетесь с политикой обработки персональных данных.',
    phone: '📱 Отправьте номер телефона кнопкой ниже или введите его вручную:',
    send_phone: '📱 Отправить телефон',
    sport: '🎾 Выберите вид спорта:',
    first_name: '✏️ Введите ваше имя:',
    last_name: '✏️ Введите вашу фамилию:',
    birth_date: '📅 Введите дату рождения в формате ДД.ММ.ГГГГ\nНапример: 15.03.1995',
    birth_date_invalid: '⚠️ Неверный формат даты. Введите как ДД.ММ.ГГГГ, например 15.03.1995',
    country: '🌍 Выберите страну:',
    city: '🏙 Выберите город:',
    district: '📍 Выберите округ Москвы:',
    role: '👤 Кто вы — игрок или тренер?',
    trainer_price: '💵 Укажите стоимость одной тренировки в рублях:',
    trainer_price_invalid: '⚠️ Введите целое число от 0 и выше (в рублях):',
    gender: '👥 Укажите ваш пол:',
    level_system: '📊 Система уровней {sport}:',
    select_level: '🎯 Выберите ваш уровень игры:',
    page: '📄 Страница {page} из {total}',
    player_level: '🎯 Выберите ваш уровень игры (NTRP):',
    table_tennis_rating: '🏓 Укажите ваш рейтинг в настольном теннисе (число):',
    default_payment: '💳 Как вы обычно делите оплату корта?',
    profile_comment: '📝 Расскажите немного о себе (или нажмите /skip):',
    photo: '📷 Добавьте фото профиля или выберите вариант ниже:',
    photo_upload: '📤 Загрузить фото',
    no_photo: 'Без фото',
    photo_from_profile: '👤 Из профиля MAX',
    photo_send: '📷 Отправьте фото сообщением:',
    vacation_tennis: '✈️ Планируете играть в отпуске?',
    vacation_country: '🌍 В какой стране будете отдыхать?',
    vacation_city: '🏙 В каком городе будете отдыхать?',
    vacation_start: '📅 Дата начала отпуска (ДД.ММ.ГГГГ):',
    vacation_end: '📅 Дата окончания отпуска (ДД.ММ.ГГГГ):',
    vacation_comment: '💬 Комментарий к поездке (необязательно):',
    vacation_date_invalid: '⚠️ Нужна сегодняшняя или будущая дата в формате ДД.ММ.ГГГГ',
    vacation_range_invalid: '⚠️ Дата окончания должна быть не раньше даты начала',
    dating_goal: '💕 Какая у вас цель знакомства?',
    dating_interests: '🎨 Выберите интересы (можно несколько):',
    dating_interests_selected: '🎯 Выбранные интересы:',
    dating_interests_hint: 'Можете выбрать ещё или нажмите «Готово»:',
    dating_interests_done: '✅ Готово',
    dating_additional: '📝 Дополнительная информация (необязательно):\n\n{fields}\n\nНапишите текст по любому из полей или /skip, чтобы пропустить:',
    meeting_time: '🕐 В какое время вам удобно встречаться?',
    complete: '🎉 Регистрация завершена! Добро пожаловать в Tennis-Play.',
    other_country: '🌍 Другая страна',
    other_city: '🏙 Другой город',
    enter_country: '🌍 Введите название страны:',
    enter_city: '🏙 Введите название города:',
  },
  profile: {
    title: '👤 Профиль',
    edit: '✏️ Редактировать',
    my_offers: '📋 Мои предложения',
    new_offer: '➕ Предложить игру',
    game_history: '📊 История игр',
    delete: '🗑 Удалить профиль',
    contact: '📞 Связаться',
    not_found: '😕 Профиль не найден',
    vacation_partner: '✈️ Найти партнёра на отдыхе',
    confirm_delete: '⚠️ Вы уверены, что хотите удалить профиль? Это действие нельзя отменить.',
    deleted: '✅ Профиль удалён',
    stats: 'Игр: {played}, побед: {wins} ({percent}%)',
    rating: 'Рейтинг: {level} ({points} очков)',
    subscription_active: '⭐ PRO до {until}',
    subscription_inactive: 'Подписка не активна',
    edit_hint: '✏️ Чтобы изменить профиль, начните регистрацию заново через /start',
    edit_menu: '✏️ Что хотите изменить?',
    edit_photo: '📷 Фото',
    edit_location: '🌍 Страна и город',
    edit_about: '📝 О себе',
    edit_payment: '💳 Оплата',
    edit_role: '🎯 Роль',
    edit_level: '🏆 Уровень',
    edit_level_done: '🏆 Уровень (изменён)',
    edit_sport: '🗂 Вид спорта',
    edit_dating_goal: '💕 Цель знакомства',
    edit_dating_interests: '🎨 Интересы',
    edit_dating_additional: '📋 Дополнительно',
    edit_meeting_time: '🕐 Время встречи',
    select_photo: '📷 Как обновить фото?',
    photo_upload: '📤 Загрузить фото',
    photo_none: '🚫 Без фото',
    photo_from_profile: '👤 Из профиля MAX',
    photo_send: '📷 Отправьте новое фото сообщением:',
    photo_updated: '✅ Фото обновлено',
    photo_deleted: '✅ Фото удалено',
    photo_no_profile: '😕 В профиле MAX нет фото',
    select_country: '🌍 Выберите страну:',
    select_city: '🏙 Выберите город ({country}):',
    select_district: '📍 Выберите округ Москвы:',
    select_payment: '💳 Выберите способ оплаты корта:',
    select_role: '👤 Выберите роль:',
    select_sport: '🎾 Выберите вид спорта:',
    select_dating_goal: '💕 Выберите цель знакомства:',
    select_dating_interests: '🎨 Выберите интересы (можно несколько):',
    enter_comment: '📝 Напишите текст о себе:',
    enter_price: '💵 Укажите стоимость тренировки в рублях:',
    enter_level: '🎯 Введите рейтинговые очки (от 0 до 2800):',
    enter_table_tennis_rating: '🏓 Введите рейтинг настольного тенниса (число):',
    enter_dating_additional: '📝 Расскажите дополнительно о себе:',
    enter_meeting_time: '🕐 Удобное время встречи:',
    rating_already_edited: 'ℹ️ Уровень можно изменить только один раз',
    rating_updated: '✅ Уровень обновлён: {level}',
    rating_invalid: '⚠️ Введите число от 0 до 2800',
    comment_updated: '✅ Раздел «О себе» обновлён',
    payment_updated: '✅ Способ оплаты обновлён',
    role_updated: '✅ Роль обновлена',
    price_updated: '✅ Стоимость тренировки обновлена',
    price_invalid: '⚠️ Введите целое число от 0 и выше',
    location_updated: '✅ Местоположение обновлено',
    sport_updated: '✅ Вид спорта обновлён',
    dating_goal_updated: '✅ Цель знакомства обновлена',
    dating_interests_updated: '✅ Интересы обновлены',
    dating_additional_updated: '✅ Дополнительная информация обновлена',
    meeting_time_updated: '✅ Время встречи обновлено',
    history_empty: '📊 История игр пока пуста.\n\nСыграйте матч и внесите счёт через «📝 Внести счет».',
    history_empty_user: '📊 У {name} пока нет сыгранных игр.',
    history_title: '📊 История игр',
    history_user_not_found: '😕 Пользователь не найден',
    history_to_profile: '👤 К анкете',
    history_game_of: '📊 Игра {current} из {total}',
    history_date: '📅 {date}',
    history_result: '🎯 {result}',
    history_win: '✅ Победа',
    history_loss: '❌ Поражение',
    history_game_type: '🗂 {type}',
    history_type_single: 'Одиночная',
    history_type_double: 'Парная',
    history_type_tournament: 'Турнирная',
    history_tournament: '🏆 {name}',
    history_player: '👤 Игрок',
    history_you: 'Вы',
    history_opponent: '👤 Соперник',
    history_pair: '👥 Пара {n}',
    history_score: '📊 Счёт: {score}',
    history_sport: '🎾 {sport}',
    history_game_id: '🆔 ID игры: {id}',
  },
  search: {
    choose_sport: '🎾 По какому виду спорта ищем партнёра?',
    all_sports: 'Все виды спорта',
    choose_country: '🌍 В какой стране ищем партнёра?',
    choose_city: '🏙 В каком городе ищем партнёра ({country})?',
    choose_district: '📍 Выберите округ в городе {city}:',
    choose_gender: '👥 Какой пол партнёра предпочитаете?',
    choose_level: '🎯 Какой уровень игры у партнёра?',
    any_district: '🏘️ Любой округ',
    any_gender: '👥 Любой пол',
    any_level: '🎯 Любой уровень',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    top_countries: '🌍 Страны, где есть игроки:',
    top_cities: '🏙 Города в стране {country}, где есть игроки:',
    countries_not_found: '😕 Пока нет стран с подходящими игроками',
    cities_not_found: '😕 Пока нет городов с подходящими игроками',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    back_to_gender: '⬅️ Назад к полу',
    no_results: '😕 В городе {city} ({country}){sport}{gender}{level} подходящих партнёров не нашлось.\nПопробуйте изменить фильтры.',
    results_title: '🔍 Найдено партнёров: {count}\n📍 {city} ({country}){sport}{gender}{level}\n\nСтраница {page} из {total}\n\nВыберите профиль:',
    choose_age: '🎂 Выберите возрастной диапазон:',
    age_any: 'Любой возраст',
    age_18_25: '18–25',
    age_26_35: '26–35',
    age_36_45: '36–45',
    age_46_55: '46–55',
    age_56_plus: '56+',
    choose_dating_goal: '💕 Какая цель знакомства у партнёра?',
    dating_goal_any: 'Любая цель',
    choose_distance: '📍 На каком расстоянии искать?',
    distance_any: 'Любое расстояние',
    distance_km: 'до {km} км',
  },
  subscription_lock: {
    title: '🔒 <b>Доступ закрыт</b>',
    price: 'Стоимость: <b>{price} руб./месяц</b>',
    go_to_payments: "Перейдите в раздел '💳 Платежи' для оформления подписки.",
    invite_friends: 'Также вы можете получить подписку бесплатно, пригласив 5 друзей.',
    invite_link: 'Ваша персональная ссылка для приглашений',
    invite_stats: 'Статистика приглашений доступна в разделе «🔗 Пригласить друга».',
    features: {
      contacts: 'Просмотр контактов доступен только для пользователей с активной подпиской Tennis-Play PRO.',
      all_players: 'Функция просмотра всех игроков доступна только для пользователей с активной подпиской Tennis-Play PRO.',
      enter_score: 'Функция внесения счета доступна только для пользователей с активной подпиской Tennis-Play PRO.',
      game_history: 'Функция просмотра истории игр игроков доступна только для пользователей с активной подпиской Tennis-Play PRO.',
    },
  },
  game_offers: {
    choose_sport: '🎾 Выберите вид спорта для предложения:',
    choose_country: '🌍 Выберите страну ({sport}):',
    choose_city: '🏙 Выберите город ({country}):',
    choose_date: '📅 Когда хотите сыграть?',
    choose_date_manual: '📅 Ввести дату вручную',
    enter_date: '📅 Введите дату в формате ДД.ММ или ДД.ММ.ГГГГ:',
    invalid_date: '⚠️ Неверный формат даты. Пример: 15.08 или 15.08.2026',
    invalid_date_past: '⚠️ Дата не может быть в прошлом. Выберите сегодня или позже.',
    choose_time: '⏰ Во сколько хотите сыграть?',
    invalid_time: '⚠️ Неверный формат времени. Пример: 18:30',
    choose_type: '🗂 Какой тип игры?',
    choose_payment: '💳 Как оплачиваем корт?',
    competitive: '🏆 Играем на счёт?',
    comment: '💬 Добавьте комментарий к предложению (или /skip):',
    published: '✅ Предложение опубликовано!',
    published_header: '🎮 Предложение #{id}',
    view_sport: '🗂 Вид спорта: {sport}',
    view_country: '🌍 Страна: {country}',
    view_city: '🏙 Город: {city}',
    view_city_district: '🏙 Город: {city} — {district}',
    view_date: '📅 Дата: {date}',
    view_time: '⏰ Время: {time}',
    view_game_type: '🔍 Тип игры: {game_type}',
    view_payment: '💳 Оплата корта: {payment}',
    view_competitive: '🏆 Игра на счёт: {value}',
    view_comment: '💬 Комментарий: {comment}',
    view_dating_goal: '💕 Цель: {value}',
    view_dating_interests: '🎯 Интересы: {value}',
    view_dating_additional: '📝 О себе: {value}',
    my_offers_empty: '📭 У вас пока нет активных предложений.\nСоздайте первое — «➕ Предложить игру».',
    my_offers_title: '🎾 Предложение #{id} ({index}/{total})',
    delete_confirm: '🗑 Удалить предложение #{id}?',
    offer_deleted: '✅ Предложение удалено',
    browse_sport: '🎾 Выберите вид спорта:',
    browse_country: '🎾 {sport}\n🌍 Выберите страну:',
    browse_city: '🎾 {sport} · {country}\n🏙 Выберите город:',
    browse_list: '🎾 {sport} · {city}\n📄 Страница {page}/{total}',
    browse_no_offers: '😕 По виду спорта «{sport}» пока нет предложений от других игроков.',
    browse_no_offers_country: '😕 В стране {country} по виду спорта «{sport}» пока нет предложений.',
    browse_no_offers_city: '😕 В городе {city} пока нет предложений от других игроков.',
    browse_no_offers_hint: '💡 Создайте своё предложение или загляните позже.',
    browse_country_item: '{country} ({count})',
    browse_city_item: '{city} ({count})',
    browse_offer_game: '➕ Предложить игру',
    browse_back_sport: '◀️ К видам спорта',
    browse_back_country: '◀️ К странам',
    browse_back_city: '◀️ К городам',
    browse_back_list: '◀️ К списку',
    respond: '✉️ Откликнуться',
    respond_comment: '💬 Напишите комментарий к отклику (или /skip):',
    respond_sent: '✅ Отклик отправлен автору предложения',
    respond_no_comment: 'Без комментария',
    dating_goal: '💕 Какая у вас цель знакомства?',
    dating_interests: '🎨 Выберите интересы (можно несколько):',
    dating_interests_done: '✅ Далее',
    dating_additional: '📝 Расскажите немного о себе:',
  },
  tournament: {
    menu: '🏆 Турниры\n\nСейчас проходит: {active_count} активных турниров\nУчаствуйте в соревнованиях и покажите свои навыки!\n\n📋 Вы можете просмотреть список доступных турниров, подать заявку на участие или посмотреть свои текущие турниры.',
    list: '📋 Просмотреть список',
    my: '🎯 Мои турниры',
    my_empty: '🎾 Вы пока не участвуете ни в одном турнире.',
    create: '➕ Создать турнир',
    card: '{name}\n{sport} · {city}\n{type} · {category}\nУчастники: {current}/{max}\nВзнос: {fee} ₽',
    card_page: '🏆 Турнир {page}/{total}\n\n{card}',
    join: '✅ Участвовать',
    leave: '🚪 Покинуть',
    pay: '💳 Оплатить взнос',
    bracket: '📊 Турнирная сетка',
    bracket_unavailable: '⚠️ Не удалось сформировать изображение сетки.\nПроверьте, что установлены Python и Pillow (см. README).',
    prev: '⬅️',
    next: '➡️',
    joined: '✅ Вы успешно зарегистрированы в турнире!',
    already_registered: '✅ Вы уже зарегистрированы в этом турнире',
    tournament_full: '😕 В этом турнире уже набран полный состав участников',
    level_mismatch: '❌ Ваш уровень ({user_level}) не соответствует уровню турнира ({tournament_level})',
    gender_mismatch: '❌ Формат турнира «{gender}» не подходит под ваш пол',
    age_mismatch: '❌ Этот турнир только для группы «{age_group}»',
    category_mismatch: '❌ Категория турнира «{category}» не соответствует вашему уровню',
    sport_mismatch: '❌ Турнир по виду спорта «{sport}», а в профиле у вас «{user_sport}»',
    left: '👋 Вы покинули турнир',
    not_found: '😕 Турнир не найден',
    unavailable: '⚠️ Этот турнир сейчас недоступен для записи',
    not_participant: 'ℹ️ Вы не записаны на этот турнир',
    payment_not_required: 'ℹ️ Для этого турнира оплата взноса не нужна',
    already_paid: '✅ Взнос уже оплачен',
    payment_email: '📧 Укажите email — на него придёт чек об оплате взноса:',
    payment_email_invalid: '⚠️ Неверный email. Пример: name@mail.com',
    payment_link: '💳 Перейдите по ссылке, чтобы оплатить взнос:',
    payment_confirmed: '✅ Взнос успешно оплачен!',
    payment_not_confirmed: '⏳ Оплата ещё не подтверждена.\nОплатите по ссылке и нажмите «Подтвердить».',
    choose_sport: '🎾 Выберите вид спорта турнира:',
    choose_country: '🌍 Выберите страну турнира:',
    choose_city: '🏙 Выберите город турнира ({country}):',
    step1: '🏆 Просмотр турниров\n\n📋 Шаг 1/5: Выберите вид спорта',
    step2: '🏆 Просмотр турниров\n\n📋 Шаг 2/5: Выберите страну\n✅ Вид спорта: {sport}',
    step2_enter: '🏆 Просмотр турниров\n\n📋 Шаг 2/5: Выберите страну или напишите название\n✅ Вид спорта: {sport}\n\nВыберите из списка или напишите название страны:',
    step3: '🏆 Просмотр турниров\n\n📋 Шаг 3/5: Выберите город или напишите название\n✅ Вид спорта: {sport}\n✅ Страна: {country}\n\nВыберите из списка или напишите название города:',
    step4_district: '🏆 Просмотр турниров\n\n📋 Шаг 4/5: Выберите часть города\n✅ Вид спорта: {sport}\n✅ Страна: {country}\n✅ Город: {city}',
    step4_gender: '🏆 Просмотр турниров\n\n📋 Шаг 4/5: Выберите формат участия\n✅ Вид спорта: {sport}\n✅ Страна: {country}\n✅ Город: {city}\n\nВыберите одиночный или парный формат:',
    step5_gender: '🏆 Просмотр турниров\n\n📋 Шаг 5/5: Выберите формат участия\n✅ Вид спорта: {sport}\n✅ Страна: {country}\n✅ Город: {city}\n✅ Район: {district}\n\nВыберите одиночный или парный формат:',
    other_country: '✏️ Другая страна',
    proposed_preview: '🏷️ {name}\n\n- Место: {location}\n- Тип: {type}\n- Формат: {gender}\n- Категория: {category}\n- Возраст: {age_group}\n- Продолжительность: {duration}\n- Участников: {count}\n\nНажмите «Участвовать» чтобы записаться на турнир.',
    proposed_missing: '⚠️ Предложение турнира не найдено. Начните просмотр заново.',
    applied_success: '✅ Вы успешно зарегистрированы в турнире!\n\n🏆 {name}\n👥 Участников: {current}/{total}',
    all_tournaments: '📋 Все турниры',
    no_list: '📭 В выбранном регионе пока нет турниров',
    you_registered: '✅ Вы записаны на этот турнир',
    create_type: '🗂 Выберите тип турнира:',
    create_gender: '👥 Выберите пол участников:',
    create_category: '🏷 Выберите категорию:',
    create_confirm: '✅ Подтвердите создание турнира:\n\n{preview}',
    create_fee: '💳 Взнос: {fee} ₽',
    create_participants: '👥 Участников: 8',
    create_done: '✅ Турнир «{name}» создан',
  },
  enter_score: {
    choose_type: '📝 Какой тип игры хотите внести?',
    single: '🎯 Одиночная игра',
    double: '👥 Парная игра',
    tournament: '🏆 Турнирная игра',
    search_opponent_prompt: '🔍 Поиск соперника\nНапишите имя или фамилию:',
    search_partner_prompt: '🔍 Ваш партнёр по паре\nНапишите имя или фамилию партнёра:',
    search_opponent1_prompt: '🔍 Первый соперник\nНапишите имя или фамилию:',
    search_opponent2_prompt: '🔍 Второй соперник\nНапишите имя или фамилию:',
    select_opponent: '👤 Выберите соперника из списка:',
    select_partner: '👤 Выберите партнёра из списка:',
    select_opponent2: '👤 Выберите второго соперника из списка:',
    users_not_found: '😕 Никого не нашли. Попробуйте другое имя или фамилию:',
    user_not_found: '😕 Пользователь не найден',
    sport_mismatch: '❌ Нельзя внести игру с игроком другого вида спорта.\n\nВаш вид спорта: {current}\nВид спорта игрока: {other}',
    select_tournament: '🏆 Выберите турнир для внесения счёта:',
    no_tournaments: '😕 Сейчас нет запущенных турниров, куда можно внести счёт',
    select_tournament_opponent: '👤 Выберите соперника из турнира:',
    no_tournament_opponents: '😕 В этом турнире нет доступных соперников',
    match_already_played: 'ℹ️ Матч с этим соперником уже сыгран',
    opponent_selected: '✅ Соперник выбран:\n👤 {name}\n\nВаш рейтинг: {rating}\n\nВыберите счёт 1-го сета:',
    pairs_formed: '✅ Пары сформированы:\n\nПара 1 (ваша):\n• {team1_p1}\n• {team1_p2}\nСредний рейтинг: {team1_avg}\n\nПара 2:\n• {team2_p1}\n• {team2_p2}\nСредний рейтинг: {team2_avg}\n\nВыберите счёт 1-го сета:',
    choose_set_score: '📊 Выберите счёт {n}-го сета:',
    super_tie: '⚡ Супертай',
    super_tiebreak: '🏆 Супертайбрейк — 3-й сет\n\nВыберите счёт супертайбрейка:',
    back_to_regular_set: '◀️ Обычный сет',
    prev_set: '⬅️ Предыдущий сет',
    next_set: '➡️ Следующий сет',
    complete_entry: '✅ Завершить ввод счёта',
    current_score: '📊 Текущий счёт:\n{score}\n\nДобавить ещё один сет?',
    add_set_yes: '✅ Да, добавить ещё сет',
    add_set_no: '❌ Нет, завершить ввод',
    score_not_entered: '⚠️ Счёт ещё не введён',
    attach_media: '📎 Хотите прикрепить фото или видео к результату?',
    add_photo: '📷 Добавить фото',
    add_video: '🎥 Добавить видео',
    send_photo: '📷 Отправьте фото сообщением:',
    send_video: '🎥 Отправьте видео сообщением:',
    confirm: '{summary}\n\n✅ Всё верно? Подтвердите результат.',
    edit_score: '✏️ Редактировать счёт',
    cancelled: '❌ Внесение счёта отменено',
    saved: '✅ Счёт сохранён, рейтинг обновлён!',
    rating_changes: '📈 Изменение рейтинга:',
    rating_line: '• {name}: {old} → {new} ({delta})',
    single_summary: '🎯 Одиночная игра\n\n👤 {player1}\n🆚\n👤 {player2}\n\n📊 Счёт: {score}',
    double_summary: '👥 Парная игра\n\nПара 1:\n• {team1_p1}\n• {team1_p2}\n\nПара 2:\n• {team2_p1}\n• {team2_p2}\n\n📊 Счёт: {score}',
    tournament_summary: '🏆 {tournament}\n\n👤 {player1}\n🆚\n👤 {player2}\n\n📊 Счёт: {score}',
  },
  payments: {
    menu: '💳 Платежи и подписка PRO',
    benefits_title: '🌟 <b>Преимущества подписки Tennis-Play PRO:</b>',
    benefits_items: [
      '• Внесение результатов матча',
      '• Просмотр анкет всех игроков',
      '• Просмотр истории игр игроков',
      '• Просмотр контактов игроков',
    ].join('\n'),
    price: 'Стоимость: <b>{price} руб./месяц</b>',
    referral: 'Также вы можете получить подписку бесплатно, пригласив 5 друзей.\nВаша персональная ссылка для приглашений доступна в разделе «{invite_section}».',
    email_note: '💡 <i>Для оформления чека потребуется ваш email</i>',
    buy: '💰 Купить подписку',
    check: '🔄 Проверить платеж',
    email: '📧 Для оформления электронного чека укажите ваш email:\n\n<i>На этот email будет отправлен чек об оплате</i>',
    email_invalid: '⚠️ Неверный email. Пример: name@mail.com',
    pay_link: '💳 Для оплаты перейдите по ссылке:\n{link}\n\nПосле успешной оплаты нажмите \'Подтвердить оплату\'\n\n📧 Чек будет отправлен на: {email}',
    continue_pay: '🔗 Перейти к оплате',
    confirm_pay: '✅ Подтвердить оплату',
    success: '🎉 Подписка успешно активирована до {until}!',
    active_until: '⭐ Подписка активна до {until}',
    already_active: '✅ У вас уже есть активная подписка до {until}',
    expired: '⌛️ Подписка истекла',
    not_confirmed: '⏳ Оплата не подтверждена. Оплатите по ссылке и нажмите «Подтвердить оплату» или «Проверить платеж».',
    no_pending: '⚠️ Нет ожидающего платежа. Нажмите «Купить подписку», чтобы создать новый.',
    create_error: '⚠️ Не удалось создать платёж. Попробуйте позже или обратитесь в поддержку.',
  },
  invite: {
    title: '🎁 Пригласите 5 друзей — получите PRO на 1 месяц бесплатно!',
    stats_title: '📊 Ваша статистика:',
    stats_count: '• Приглашено друзей: {count}/5',
    how_title: 'ℹ️ Как это работает:',
    how_items: [
      '• Пригласите 5 друзей в бот',
      '• Каждый друг должен пройти регистрацию',
      '• Вы получите бесплатную подписку на 1 месяц',
    ].join('\n'),
    link_title: '📎 Ваша реферальная ссылка:',
    share_title: '📤 Как поделиться:',
    share_steps: [
      '1. Скопируйте ссылку выше',
      '2. Отправьте её друзьям',
      '3. Следите за прогрессом в этом разделе',
    ].join('\n'),
    share: '📤 Поделиться',
  },
  players_search: {
    choose_sport: '🎾 По какому виду спорта ищем игроков?',
    choose_country: '🌍 В какой стране ищем игроков?',
    choose_city: '🏙 В каком городе ищем игроков ({country})?',
    top_countries: '🌍 Страны, где есть игроки:',
    top_cities: '🏙 Города в стране {country}, где есть игроки:',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    countries_not_found: '😕 Пока нет стран с игроками',
    cities_not_found: '😕 Пока нет городов с игроками',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    sport_suffix: ', вид спорта: {sport}',
    no_results: '😕 В городе {city} ({country}){sport} игроков не нашлось.',
    results_title: '🔍 Найдено игроков: {count}\n📍 {city} ({country}){sport}\n\nСтраница {page} из {total}\n\nВыберите профиль:',
  },
  coach_search: {
    choose_sport: '🎾 Выберите вид спорта:',
    any_price: '💵 Любая цена',
    choose_price: '💵 Выберите диапазон стоимости урока:',
    choose_country: '🌍 В какой стране ищем тренеров?',
    choose_city: '🏙 В каком городе ищем тренеров ({country})?',
    top_countries: '🌍 Страны, где есть тренеры:',
    top_cities: '🏙 Города в стране {country}, где есть тренеры:',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    countries_not_found: '😕 Пока нет стран с тренерами',
    cities_not_found: '😕 Пока нет городов с тренерами',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_price: '⬅️ Назад к цене',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    sport_suffix: ', вид спорта: {sport}',
    price_suffix: ', цена: {price_min}-{price_max} руб.',
    no_results: '😕 В городе {city} ({country}){sport}{price} тренеров не нашлось.',
    results_title: '🔍 Найдено тренеров: {count}\n📍 {city} ({country}){sport}{price}\n\nСтраница {page} из {total}\n\nВыберите профиль:',
    rub_short: ' ₽',
  },
  more: {
    title: '🔍 Ещё',
    tours: '✈️ Туры',
    all_players: '👥 Все игроки',
    find_coach: '🎓 Найти тренера',
    about: 'ℹ️ О проекте',
    contacts: '📞 Контакты',
    contacts_text: 'По вопросам работы бота и предложениям пишите на:\n📧 info@tennis-play.com',
    profile: '👤 Мой профиль',
    multi_day_tournaments: '🏆 Многодневные турниры',
    weekend_tournaments: '🏆 Турниры выходного дня',
    website: '🌐 Перейти на сайт',
  },
  admin: {
    menu: '🛠 Админ-панель',
    stats: '📊 Статистика',
    broadcast: '📢 Рассылка',
    broadcast_prompt: '📢 Отправьте текст рассылки:',
    broadcast_confirm: '📢 Отправить эту рассылку?\n\n{text}',
    broadcast_empty: '⚠️ Текст рассылки пуст',
    broadcast_done: '✅ Рассылка отправлена: {count}',
    users_count: '👥 Пользователей: {count}',
    ban: '🚫 Забанить',
    delete_user: '🗑 Удалить',
  },
  tours: {
    menu: '✈️ Туры',
    create: '➕ Создать тур',
    browse: '🔍 Найти игроков в туре',
    choose_sport: '🎾 По какому виду спорта ищем игроков в туре?',
    choose_country: '🌍 В какой стране ищем игроков в туре?',
    choose_city: '🏙 В каком городе ищем игроков в туре ({country})?',
    results: '✈️ Найдено игроков в туре: {count}\n📍 {city} ({country})\n\nВыберите профиль:',
    no_results: '😕 В городе {city} ({country}) пока нет игроков с активным туром.',
    published: '✅ Тур опубликован!',
  },
  channels: {
    new_trainer: '👨‍🏫 <b>Новый тренер присоединился к платформе!</b>',
    new_player: '🎾 <b>Новый игрок присоединился к сообществу!</b>',
    trainer: '<b>Тренер:</b>',
    player: '<b>Игрок:</b>',
    city: '<b>Город:</b>',
    age: '<b>Возраст:</b>',
    gender: '<b>Пол:</b>',
    sport: '<b>Вид спорта:</b>',
    price: '<b>Стоимость:</b>',
    level: '<b>Уровень игры:</b>',
    rating: '<b>Рейтинг:</b>',
    dating_goal: '<b>Цель знакомства:</b>',
    interests: '<b>Интересы:</b>',
    about: '<b>О себе:</b>',
    meeting_time: '<b>Время встречи:</b>',
    court_payment: '<b>Оплата корта:</b>',
    tournament_game_completed: '🏆 <b>Завершена турнирная игра!</b>',
    tournament: '<b>Турнир:</b>',
    score: '<b>Счёт:</b>',
    winner_beats: '{winner} выиграл у {loser}',
    single_game_completed: '🎾 <b>Завершена одиночная игра!</b>',
    winner: '<b>Победитель:</b>',
    loser: '<b>Проигравший:</b>',
    rating_change: '<b>Изменение рейтинга:</b>',
    double_game_completed: '🎾 <b>Завершена парная игра!</b>',
    winning_team: '<b>Победившая команда:</b>',
    losing_team: '<b>Проигравшая команда:</b>',
    view_tournament: '👀 Смотреть турнир',
    tournament_info: '🏆 <b>Информация о турнире:</b>',
    dating_profile: '💕 <b>Анкета для знакомств</b>',
    date_time: '<b>Дата и время:</b>',
    business_breakfast_offer: '☕️ <b>Предложение бизнес-завтрака</b>',
    beer_meeting_offer: '🍻 <b>Предложение встречи за пивом</b>',
    activity_offer: '🏃 <b>Предложение активности</b>',
    game_offer: '🎾 <b>Предложение игры</b>',
    game_type: '<b>Тип игры:</b>',
    payment: '<b>Оплата:</b>',
    comment: '<b>Комментарий:</b>',
    competitive_game: '🏆 <b>Тип игры:</b> На счёт',
    tour_title: '✈️ <b>Тур по {sport}</b>',
    destination: '<b>Направление:</b>',
    dates: '<b>Даты:</b>',
    tournament_name: '<b>{name}</b>',
    tournament_type: '<b>Тип:</b>',
    category: '<b>Категория:</b>',
    tournament_level: '<b>Уровень:</b>',
    age_group: '<b>Возраст:</b>',
    duration: '<b>Продолжительность:</b>',
    participants: '<b>Участников:</b>',
    description: '<b>Описание:</b>',
    join: '✅ Участвовать',
    new_participant: '🎉 <b>Новый участник в турнире!</b>',
    join_and_participate: 'Присоединяйтесь и участвуйте!',
    tournament_started: '🏁 <b>Турнир начался!</b>',
    tournament_follow: 'Турнир запущен! Следите за результатами.',
    tournament_finished: '🏁 <b>Турнир завершён!</b>',
    summary: '<b>Итоги:</b>',
    congratulations: '🎉 Поздравляем победителей!',
    view_tournament_button: '🏆 Смотреть турнир',
    unknown_tournament: 'Неизвестный турнир',
    years_old: '{age} лет',
    rating_points: '({points} очков)',
    table_tennis_rating: '🏓 Рейтинг: {rating}',
  },
  start: {
    registered_welcome: `👋 Здравствуйте, {name}!

🏆 Ваш рейтинг: {rating}
🎾 Сыграно игр: {games}
✅ Побед: {wins}

Вы в официальном боте Tennis-Play. Выберите действие в меню ниже.`,
  },
  main_menu_title: '🏠 Главное меню Tennis-Play',
} as const;

export const MENU_LABELS = [
  TXT.menu.search_partner,
  TXT.menu.game_offers,
  TXT.menu.tournaments,
  TXT.menu.enter_score,
  TXT.menu.invite,
  TXT.menu.payments,
  TXT.menu.more,
] as const;
