export function fmt(template: string, params: Record<string, string | number>): string {
  return Object.entries(params).reduce(
    (text, [k, v]) => text.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v)),
    template,
  );
}

export const TXT = {
  common: {
    back: '◀️ Назад',
    cancel: '❌ Отмена',
    skip: '⏭ Пропустить',
    yes: '✅ Да',
    no: '❌ Нет',
    main_menu: '🏠 Главное меню',
    next: '▶️ Далее',
    prev: '◀️ Назад',
    confirm: '✅ Подтвердить',
    banned: '⛔ Вы заблокированы и не можете пользоваться ботом.',
    private_only: 'Бот работает только в личных чатах.',
    error: 'Произошла ошибка. Попробуйте позже.',
    not_registered: 'Сначала пройдите регистрацию — /start',
  },
  menu: {
    search_partner: '🎾 Поиск партнера',
    game_offers: '⏱ Предложение игр',
    tournaments: '🏆 Турниры',
    enter_score: '📝 Внести счет',
    invite: '🔗 Пригласить друга',
    payments: '💳 Платежи',
    more: '🔍 Еще',
  },
  registration: {
    welcome:
      '👋 Добро пожаловать в бот Tennis-Play!\n\nДля начала пройдите краткую регистрацию.\n\nНачиная регистрацию, вы соглашаетесь с политикой обработки персональных данных и даёте согласие на обработку данных.',
    phone: 'Отправьте номер телефона кнопкой ниже или введите вручную:',
    send_phone: '📱 Отправить телефон',
    sport: 'Выберите вид спорта:',
    first_name: 'Введите имя:',
    last_name: 'Введите фамилию:',
    birth_date: 'Введите дату рождения (ДД.ММ.ГГГГ):',
    birth_date_invalid: 'Неверный формат даты. Используйте ДД.ММ.ГГГГ',
    country: 'Выберите страну:',
    city: 'Выберите город:',
    district: 'Выберите округ Москвы:',
    role: 'Вы игрок или тренер?',
    trainer_price: 'Укажите цену тренировки (руб):',
    trainer_price_invalid: 'Введите целое неотрицательное число (руб):',
    gender: 'Укажите пол:',
    level_system: 'Система уровней {sport}:',
    select_level: 'Выберите ваш уровень:',
    page: 'Страница {page} из {total}',
    player_level: 'Выберите уровень игры (NTRP):',
    table_tennis_rating: 'Укажите ваш рейтинг настольного тенниса (число):',
    default_payment: 'Как обычно делите оплату корта?',
    profile_comment: 'Расскажите о себе (или /skip):',
    photo: 'Загрузите фото или выберите вариант:',
    photo_upload: '📤 Загрузить фото',
    no_photo: 'Без фото',
    photo_from_profile: '👤 Из профиля MAX',
    photo_send: 'Отправьте фото:',
    vacation_tennis: 'Планируете играть в отпуске?',
    vacation_country: 'Страна отдыха:',
    vacation_city: 'Город отдыха:',
    vacation_start: 'Дата начала отпуска (ДД.ММ.ГГГГ):',
    vacation_end: 'Дата окончания отпуска (ДД.ММ.ГГГГ):',
    vacation_comment: 'Комментарий к туру:',
    vacation_date_invalid: 'Неверная дата. Нужна сегодняшняя или будущая дата в формате ДД.ММ.ГГГГ',
    vacation_range_invalid: 'Дата окончания должна быть не раньше даты начала (ДД.ММ.ГГГГ)',
    dating_goal: 'Цель знакомства:',
    dating_interests: 'Выберите интересы (можно несколько):',
    dating_interests_selected: '🎯 Выбранные интересы:',
    dating_interests_hint: 'Выберите ещё или нажмите «Готово» для продолжения:',
    dating_interests_done: '✅ Готово',
    dating_additional: '📝 Дополнительная информация (необязательно, можно пропустить):\n\n{fields}\n\nНапишите информацию по любому из полей или /skip для пропуска:',
    meeting_time: 'Удобное время встречи:',
    complete: '✅ Регистрация завершена!',
    other_country: '🌍 Другая страна',
    other_city: '🏙 Другой город',
    enter_country: 'Введите страну:',
    enter_city: 'Введите город:',
  },
  profile: {
    title: '👤 Профиль',
    edit: '✏️ Редактировать',
    my_offers: '📋 Мои предложения',
    new_offer: '➕ Предложить игру',
    game_history: '📊 История игр',
    delete: '🗑 Удалить профиль',
    contact: '📞 Связаться',
    contact_pro: 'Контакты доступны с PRO-подпиской',
    not_found: 'Профиль не найден',
    vacation_partner: '✈️ Найти партнёра на отдыхе',
    confirm_delete: 'Вы уверены, что хотите удалить профиль?',
    deleted: 'Профиль удалён',
    stats: 'Игр: {played}, побед: {wins} ({percent}%)',
    rating: 'Рейтинг: {level} ({points} очков)',
    subscription_active: 'PRO до {until}',
    subscription_inactive: 'Подписка не активна',
    edit_hint: 'Редактирование профиля — начните регистрацию заново через /start',
    edit_menu: '✏️ Что хотите изменить?',
    edit_photo: '📷 Фото',
    edit_location: '🌍 Страна и город',
    edit_about: '📝 О себе',
    edit_payment: '💳 Оплата',
    edit_role: '🎯 Роль',
    edit_level: '🏆 Уровень',
    edit_level_done: '🏆 Уровень (изменён)',
    edit_sport: '🗂 Вид спорта',
    edit_dating_goal: '💕 Цель знакомства',
    edit_dating_interests: '🎨 Интересы',
    edit_dating_additional: '📋 Дополнительно',
    edit_meeting_time: '🕐 Время встречи',
    select_photo: 'Выберите способ обновления фото:',
    photo_upload: '📤 Загрузить фото',
    photo_none: '🚫 Без фото',
    photo_from_profile: '👤 Из профиля MAX',
    photo_send: 'Отправьте новое фото:',
    photo_updated: '✅ Фото обновлено',
    photo_deleted: '✅ Фото удалено',
    photo_no_profile: 'В профиле MAX нет фото',
    select_country: 'Выберите страну:',
    select_city: 'Выберите город ({country}):',
    select_district: 'Выберите округ Москвы:',
    select_payment: 'Выберите тип оплаты:',
    select_role: 'Выберите роль:',
    select_sport: 'Выберите вид спорта:',
    select_dating_goal: 'Выберите цель:',
    select_dating_interests: 'Выберите интересы (можно несколько):',
    enter_comment: 'Введите текст о себе:',
    enter_price: 'Укажите стоимость тренировки (руб):',
    enter_level: 'Введите рейтинговые очки (0–2800):',
    enter_table_tennis_rating: 'Введите рейтинг настольного тенниса (число):',
    enter_dating_additional: 'Расскажите дополнительно о себе:',
    enter_meeting_time: 'Удобное время встречи:',
    rating_already_edited: 'Уровень можно изменить только один раз',
    rating_updated: '✅ Уровень обновлён: {level}',
    rating_invalid: 'Введите число от 0 до 2800',
    comment_updated: '✅ О себе обновлено',
    payment_updated: '✅ Оплата обновлена',
    role_updated: '✅ Роль обновлена',
    price_updated: '✅ Стоимость обновлена',
    price_invalid: 'Введите целое неотрицательное число',
    location_updated: '✅ Местоположение обновлено',
    sport_updated: '✅ Вид спорта обновлён',
    dating_goal_updated: '✅ Цель обновлена',
    dating_interests_updated: '✅ Интересы обновлены',
    dating_additional_updated: '✅ Дополнительно обновлено',
    meeting_time_updated: '✅ Время встречи обновлено',
    history_empty: '📊 История игр пуста.\n\nСыграйте матч и внесите счёт через «📝 Внести счет».',
    history_empty_user: '📊 У {name} пока нет сыгранных игр.',
    history_title: '📊 История игр',
    history_pro: '🔒 Просмотр истории игр других игроков доступен с PRO-подпиской.\n\nПерейдите в раздел «💳 Платежи».',
    history_user_not_found: 'Пользователь не найден',
    history_to_profile: '👤 К анкете',
    history_game_of: '📊 Игра {current} из {total}',
    history_date: '📅 {date}',
    history_result: '🎯 {result}',
    history_win: '✅ Победа',
    history_loss: '❌ Поражение',
    history_game_type: '🗂 {type}',
    history_type_single: 'Одиночная',
    history_type_double: 'Парная',
    history_type_tournament: 'Турнирная',
    history_tournament: '🏆 {name}',
    history_player: '👤 Игрок',
    history_you: 'Вы',
    history_opponent: '👤 Соперник',
    history_pair: '👥 Пара {n}',
    history_score: '📊 Счёт: {score}',
    history_sport: '🎾 {sport}',
    history_game_id: '🆔 ID игры: {id}',
  },
  search: {
    choose_sport: '🎾 Выберите вид спорта для поиска партнёра:',
    all_sports: 'Все виды спорта',
    choose_country: '🌍 Выберите страну для поиска партнёра:',
    choose_city: '🏙 Выберите город для поиска партнёра в {country}:',
    choose_district: '🏘️ Выберите округ в городе {city}:',
    choose_gender: '👥 Выберите пол партнёра:',
    choose_level: '🎯 Выберите уровень игры партнёра:',
    any_district: '🏘️ Любой округ',
    any_gender: '👥 Любой пол',
    any_level: '🎯 Любой уровень',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    top_countries: '🌍 Топ стран с пользователями:',
    top_cities: '🌍 Топ городов с пользователями в {country}:',
    countries_not_found: '❌ Нет стран с пользователями',
    cities_not_found: '❌ Нет городов с пользователями',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    back_to_gender: '⬅️ Назад к полу',
    no_results: '😕 В городе {city} ({country}){sport}{gender}{level} не найдено подходящих партнёров.',
    results_title: '🔍 Найдено {count} партнёров в городе {city} ({country}){sport}{gender}{level}:\n\nСтраница {page} из {total}\n\nВыберите профиль для просмотра:',
    choose_age: '🎂 Выберите возрастной диапазон партнёра:',
    age_any: 'Любой возраст',
    age_18_25: '18–25',
    age_26_35: '26–35',
    age_36_45: '36–45',
    age_46_55: '46–55',
    age_56_plus: '56+',
    choose_dating_goal: '💕 Выберите цель знакомства партнёра:',
    dating_goal_any: 'Любая цель',
    choose_distance: '📍 Выберите расстояние:',
    distance_any: 'Любое расстояние',
    distance_km: 'до {km} км',
  },
  game_offers: {
    paywall_title: '🔒 Доступ закрыт',
    paywall_limit: 'Вы использовали все бесплатные предложения игры (максимум 1).',
    paywall_subscription_info: 'Функция предложения игры доступна только для пользователей с активной подпиской Tennis-Play PRO.',
    paywall_price: 'Стоимость: {price} руб./месяц',
    paywall_go_payments: "Перейдите в раздел '{payments_section}' для оформления подписки.",
    paywall_invite_friends: 'Также вы можете получить подписку бесплатно, пригласив 5 друзей.',
    paywall_invite_link: 'Ваша персональная ссылка для приглашений',
    paywall_invite_stats: 'Статистика приглашений доступна в разделе «{invite_section}».',
    choose_sport: 'Выберите спорт для предложения:',
    choose_country: 'Выберите страну ({sport}):',
    choose_city: 'Выберите город ({country}):',
    choose_date: 'Выберите дату:',
    choose_date_manual: '📅 Ввести дату вручную',
    enter_date: 'Введите дату (ДД.ММ или ДД.ММ.ГГГГ):',
    invalid_date: 'Неверный формат даты',
    invalid_date_past: 'Дата не может быть в прошлом',
    choose_time: 'Выберите время:',
    invalid_time: 'Неверный формат времени',
    choose_type: 'Тип игры:',
    choose_payment: 'Оплата корта:',
    competitive: 'Игра на счёт?',
    comment: 'Комментарий к предложению (или /skip):',
    published: '✅ Предложение создано',
    published_header: '🎮 Предложение #{id}',
    view_sport: '🗂 Вид спорта: {sport}',
    view_country: '🌍 Страна: {country}',
    view_city: '🏙 Город: {city}',
    view_city_district: '🏙 Город: {city} - {district}',
    view_date: '📅 Дата: {date}',
    view_time: '⏰ Время: {time}',
    view_game_type: '🔍 Тип игры: {game_type}',
    view_payment: '💳 Способ оплаты: {payment}',
    view_competitive: '🏆 Игра на счет: {value}',
    view_comment: '💬 Комментарий: {comment}',
    view_dating_goal: '💕 Цель: {value}',
    view_dating_interests: '🎯 Интересы: {value}',
    view_dating_additional: '📝 О себе: {value}',
    remaining_offers: '📊 Бесплатных предложений осталось: {remaining}/1',
    subscribe_unlimited: '💳 Оформите подписку для неограниченного создания предложений!',
    subscription_active_offer: '✅ Подписка активна — неограниченное создание предложений!',
    unlimited_female: '♾ Безлимитные предложения для вас!',
    my_offers_empty: 'У вас нет активных предложений',
    my_offers_title: '🎾 Предложение #{id} ({index}/{total})',
    delete_confirm: 'Удалить предложение #{id}?',
    offer_deleted: '✅ Предложение удалено',
    browse_sport: 'Выберите спорт:',
    browse_country: 'Предложения · {sport}\nВыберите страну:',
    browse_city: '{sport} · {country}\nВыберите город:',
    browse_list: '{sport} · {city}\nСтр. {page}/{total}',
    browse_no_offers: '❌ Нет предложений от других игроков по {sport}',
    browse_no_offers_country: '❌ Нет предложений в {country} ({sport})',
    browse_no_offers_city: '❌ В {city} нет предложений от других игроков',
    browse_no_offers_hint: 'Создайте своё предложение или загляните позже.',
    browse_country_item: '{country} ({count})',
    browse_city_item: '{city} ({count})',
    browse_offer_game: '➕ Предложить игру',
    browse_back_sport: '◀️ К видам спорта',
    browse_back_country: '◀️ К странам',
    browse_back_city: '◀️ К городам',
    browse_back_list: '◀️ К списку',
    respond: '✉️ Откликнуться',
    respond_comment: 'Напишите комментарий к отклику (или /skip):',
    respond_sent: '✅ Отклик отправлен автору',
    respond_no_comment: 'Без комментария',
    dating_goal: 'Цель знакомства:',
    dating_interests: 'Выберите интересы (можно несколько):',
    dating_interests_done: '✅ Далее',
    dating_additional: 'Расскажите о себе:',
  },
  tournament: {
    menu: '🏆 Турниры',
    list: 'Список турниров',
    my: 'Мои турниры',
    my_empty: 'Вы пока не записаны ни на один турнир',
    create: '➕ Создать турнир',
    card: '{name}\n{sport} · {city}\n{type} · {category}\nУчастники: {current}/{max}\nВзнос: {fee} ₽',
    join: '📝 Подать заявку',
    leave: '🚪 Покинуть',
    pay: '💳 Оплатить взнос',
    bracket: '📊 Сетка',
    joined: 'Вы записаны на турнир',
    left: 'Вы покинули турнир',
    not_found: 'Турнир не найден',
    unavailable: 'Турнир недоступен',
    not_participant: 'Вы не записаны на этот турнир',
    payment_not_required: 'Оплата не требуется',
    already_paid: 'Взнос уже оплачен',
    payment_email: '📧 Укажите email для чека об оплате взноса:',
    payment_email_invalid: 'Неверный email',
    payment_link: 'Перейдите по ссылке для оплаты взноса',
    payment_confirmed: '✅ Взнос оплачен',
    payment_not_confirmed: 'Оплата ещё не подтверждена. Оплатите по ссылке и нажмите «Подтвердить».',
    choose_city: '🏙 Выберите город:',
    no_list: 'В выбранном регионе пока нет турниров',
  },
  enter_score: {
    pro_required: 'Внесение счёта доступно с PRO-подпиской',
    choose_type: 'Выберите тип игры:',
    single: '🎯 Одиночная игра',
    double: '👥 Парная игра',
    tournament: '🏆 Турнирная игра',
    search_opponent_prompt: 'Поиск соперника\nНапишите имя или фамилию соперника:',
    search_partner_prompt: 'Ваш партнёр по паре\nНапишите имя или фамилию партнёра:',
    search_opponent1_prompt: 'Поиск первого соперника\nНапишите имя или фамилию первого соперника:',
    search_opponent2_prompt: 'Поиск второго соперника\nНапишите имя или фамилию второго соперника:',
    select_opponent: 'Выберите соперника из списка:',
    select_partner: 'Выберите партнёра из списка:',
    select_opponent2: 'Выберите второго соперника из списка:',
    users_not_found: 'Пользователи не найдены. Попробуйте ещё раз:',
    user_not_found: 'Пользователь не найден',
    sport_mismatch: '❌ Нельзя играть с игроками другого вида спорта!\n\nВаш вид спорта: {current}\nВид спорта игрока: {other}',
    select_tournament: '🏆 Выберите турнир для внесения счёта:',
    no_tournaments: '❌ Нет запущенных турниров для внесения счёта',
    select_tournament_opponent: 'Выберите соперника из турнира:',
    no_tournament_opponents: '❌ Нет доступных соперников в этом турнире',
    match_already_played: 'Матч с этим соперником уже сыгран',
    opponent_selected: 'Вы выбрали соперника:\n👤 {name}\n\nВаш рейтинг: {rating}\n\nВыберите счёт 1-го сета:',
    pairs_formed: 'Пары сформированы:\n\nПара 1 (ваша):\n• {team1_p1}\n• {team1_p2}\nСредний рейтинг: {team1_avg}\n\nПара 2:\n• {team2_p1}\n• {team2_p2}\nСредний рейтинг: {team2_avg}\n\nВыберите счёт 1-го сета:',
    choose_set_score: 'Выберите счёт {n}-го сета:',
    super_tie: '⚡ Супертай',
    super_tiebreak: '🏆 Супертайбрейк — 3-й сет\n\nВыберите счёт супертайбрейка:',
    back_to_regular_set: '◀️ Обычный сет',
    prev_set: '⬅️ Предыдущий сет',
    next_set: '➡️ Следующий сет',
    complete_entry: '✅ Завершить ввод счёта',
    current_score: 'Текущий счёт:\n{score}\n\nДобавить ещё один сет?',
    add_set_yes: '✅ Да, добавить ещё сет',
    add_set_no: '❌ Нет, завершить ввод',
    score_not_entered: 'Счёт не введён',
    attach_media: 'Хотите прикрепить фото или видео к результату?',
    add_photo: '📷 Добавить фото',
    add_video: '🎥 Добавить видео',
    send_photo: 'Отправьте фото:',
    send_video: 'Отправьте видео:',
    confirm: '{summary}\n\nПодтвердите результат?',
    edit_score: '✏️ Редактировать счёт',
    cancelled: '❌ Внесение счёта отменено',
    saved: '✅ Счёт сохранён, рейтинг обновлён',
    rating_changes: '📈 Изменение рейтинга:',
    rating_line: '• {name}: {old} → {new} ({delta})',
    single_summary: '🎯 Одиночная игра\n\n👤 {player1}\n🆚\n👤 {player2}\n\n📊 Счёт: {score}',
    double_summary: '👥 Парная игра\n\nПара 1:\n• {team1_p1}\n• {team1_p2}\n\nПара 2:\n• {team2_p1}\n• {team2_p2}\n\n📊 Счёт: {score}',
    tournament_summary: '🏆 {tournament}\n\n👤 {player1}\n🆚\n👤 {player2}\n\n📊 Счёт: {score}',
  },
  payments: {
    menu: '💳 Платежи и подписка PRO',
    benefits_title: '🌟 Преимущества подписки Tennis-Play PRO:',
    benefits_items: [
      '• Внесение результатов матча',
      '• Просмотр анкет всех игроков',
      '• Просмотр история игр игроков',
      '• Безлимитные заявки на игры',
    ].join('\n'),
    price: 'Стоимость: {price} руб./месяц',
    referral: 'Также вы можете получить подписку бесплатно, пригласив 5 друзей.\nВаша персональная ссылка для приглашений доступна в разделе «{invite_section}».',
    email_note: '💡 Для оформления чека потребуется ваш email',
    buy: '💳 Купить PRO',
    email: '📧 Для оформления электронного чека укажите ваш email:\n\nНа этот email будет отправлен чек об оплате',
    email_invalid: 'Неверный email',
    pay_link: 'Перейдите по ссылке для оплаты',
    continue_pay: '💳 Перейти к оплате',
    confirm_pay: '✅ Подтвердить оплату',
    success: '✅ PRO активирована до {until}',
    active_until: 'Подписка активна до {until}',
    expired: 'Подписка истекла',
    not_confirmed: 'Оплата не подтверждена',
  },
  invite: {
    title: '👥 Получите бесплатную подписку на 1 месяц за каждых 5 друзей!',
    stats_title: '📊 Ваша статистика:',
    stats_count: '• Приглашено друзей: {count}/5',
    how_title: '🎁 Как это работает:',
    how_items: [
      '• Пригласите 5 друзей в бот',
      '• Каждый друг должен пройти регистрацию',
      '• Получите бесплатную подписку на 1 месяц',
    ].join('\n'),
    link_title: '📎 Ваша реферальная ссылка:',
    share_title: '📤 Как делиться:',
    share_steps: [
      '1. Скопируйте ссылку выше',
      '2. Отправьте друзьям',
      '3. Следите за прогрессом в этом разделе',
    ].join('\n'),
    share: '📤 Поделиться',
  },
  players_search: {
    choose_sport: '🏆 Выберите вид спорта для поиска игроков:',
    choose_country: '🌍 Выберите страну для поиска игроков:',
    choose_city: '🏙 Выберите город для поиска игроков в {country}:',
    top_countries: '🌍 Топ стран с игроками:',
    top_cities: '🏙 Топ городов в {country} с игроками:',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    countries_not_found: '❌ Нет стран с игроками',
    cities_not_found: '❌ Нет городов с игроками',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    sport_suffix: ', вид спорта: {sport}',
    no_results: '😕 В городе {city} ({country}){sport} не найдено игроков.',
    results_title: '🔍 Найдено {count} игроков в городе {city} ({country}){sport}:\n\nСтраница {page} из {total}\n\nВыберите профиль для просмотра:',
  },
  coach_search: {
    choose_sport: '🏆 Выберите вид спорта:',
    any_price: '💵 Любая цена',
    choose_price: '💵 Выберите диапазон стоимости урока:',
    choose_country: '🌍 Выберите страну для поиска тренеров:',
    choose_city: '🏙 Выберите город для поиска тренеров в {country}:',
    top_countries: '🌍 Топ стран с тренерами:',
    top_cities: '🏙 Топ городов в {country} с тренерами:',
    country_item: '{country} ({count})',
    city_item: '{city} ({count})',
    other_countries: '🌎 Другие страны ({count})',
    other_cities: '🏙 Другие города ({count})',
    countries_not_found: '❌ Нет стран с тренерами',
    cities_not_found: '❌ Нет городов с тренерами',
    back_to_sport: '⬅️ Назад к виду спорта',
    back_to_price: '⬅️ Назад к цене',
    back_to_countries: '⬅️ Назад к странам',
    back_to_cities: '⬅️ Назад к городам',
    sport_suffix: ', вид спорта: {sport}',
    price_suffix: ', цена: {price_min}-{price_max} руб.',
    no_results: '😕 В городе {city} ({country}){sport}{price} не найдено тренеров.',
    results_title: '🔍 Найдено {count} тренеров в городе {city} ({country}){sport}{price}:\n\nСтраница {page} из {total}\n\nВыберите профиль для просмотра:',
    rub_short: ' ₽',
  },
  more: {
    title: '🔍 Ещё',
    tours: '✈️ Туры',
    all_players: '👥 Все игроки',
    find_coach: '🎓 Найти тренера',
    about: 'ℹ️ О проекте',
    contacts: '📞 Контакты',
    contacts_text: 'По всем вопросам работы бота и предложениям пишите на адрес:\n📧 info@tennis-play.com',
    profile: '👤 Мой профиль',
    multi_day_tournaments: '🏆 Многодневные турниры',
    weekend_tournaments: '🏆 Турниры выходного дня',
    website: 'Перейти на сайт',
    pro_required: 'Доступно с PRO-подпиской',
  },
  admin: {
    menu: '🛠 Админ-панель',
    stats: '📊 Статистика',
    broadcast: '📢 Рассылка',
    broadcast_prompt: 'Отправьте текст рассылки:',
    broadcast_confirm: 'Отправить рассылку?\n\n{text}',
    broadcast_empty: 'Текст рассылки пуст',
    broadcast_done: '✅ Рассылка отправлена: {count}',
    users_count: 'Пользователей: {count}',
    ban: '🚫 Забанить',
    delete_user: '🗑 Удалить',
  },
  tours: {
    menu: '✈️ Туры',
    create: '➕ Создать тур',
    browse: '🔍 Найти партнёра',
    published: '✅ Тур опубликован',
  },
  channels: {
    new_player: '🆕 Новый игрок: {name}, {sport}, {city}',
    new_offer: '📣 Новое предложение: {sport} {city} {date} {time}',
    game_result: '🏆 Результат: {score}',
    new_tour: '✈️ Новый тур: {city} {dates}',
    new_tournament: '🏆 Новый турнир: {name}',
  },
  start: {
    registered_welcome: `👋 Здравствуйте, {name}!

🏆 Ваш рейтинг: {rating}
🎾 Сыграно игр: {games}
✅ Побед: {wins}

Вы зарегистрированы в официальном боте`,
  },
  main_menu_title: 'Главное меню Tennis-Play',
} as const;

export const MENU_LABELS = [
  TXT.menu.search_partner,
  TXT.menu.game_offers,
  TXT.menu.tournaments,
  TXT.menu.enter_score,
  TXT.menu.invite,
  TXT.menu.payments,
  TXT.menu.more,
] as const;
